# Environment Configuration for "PotSim: A Large-Scale Simulated Dataset for Benchmarking 
# Machine Learning Techniques on Potato Crop"
#
# This file defines the Conda environment required to run the code associated with our research.
# It uses Conda (or Mamba) to manage most packages and explicitly uses pip with a specific 
# index URL to install PyTorch compiled for CUDA 12.4.
#
# To create this environment:
# 1. Install Conda: https://conda.io/projects/conda/en/latest/user-guide/install
# 2. Navigate to the project directory containing this file in your terminal.
# 3. Run: conda env create -f environment.yml
#    (or: mamba env create -f environment.yml)
# 4. Activate the environment: conda activate aitorch
#
# IMPORTANT HARDWARE NOTE: This environment installs PyTorch compiled for CUDA 12.4.
# It requires an NVIDIA GPU with drivers compatible with CUDA 12.4.
# CPU-only execution or other GPU types are not directly supported by this configuration.
name: potsim_env
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  # --- Conda Packages ---
  - python=3.12
  - pip=25.1
  - cuda-version[version=">=12.4,<12.5"]
  - jupyterlab=4.4
  - ipykernel=6.29
  - nb_conda_kernels=2.5
  - numpy=2.2
  - scipy=1.15
  - pandas=2.2
  - pyarrow=19.0
  - polars=1.27
  - matplotlib=3.10
  - seaborn=0.13
  - scikit-learn=1.6
  - py-xgboost=3.0
  - shap=0.47
  - tqdm=4.67
  # --- Pip Packages ---
  - pip:
      # Install PyTorch, torchvision, torchaudio with specific CUDA via pip
      - torch==2.5.1 --index-url https://download.pytorch.org/whl/cu124
      - torchvision==0.20.1 --index-url https://download.pytorch.org/whl/cu124
      - torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu124
      - torchmetrics==1.7.1
      - torchinfo==1.8.0
